apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
  - name: nodeapp-service
    protocol: TCP
    port: 3000
    nodePort: 31111